name: Docker Build and Push (on Tag)

on:
  push:
    tags:
      - '*.*.*' # Триггер при пуше тега, соответствующего формату "X.Y.Z"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Путь к вашему Dockerfile
          push: false # Собираем, но пока не пушим
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest # Опционально: также помечаем как latest

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest # Опционально: также помечаем как latest

      - name: Verify pushed image (optional)
        run: |
          echo "Docker image pushed successfully with tags:"
          echo "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_version.outputs.VERSION }}"
          echo "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest"
